Repository NetApp/cake, pull requests merged in 2020-05, with the labels that each got.

#46 Generate ssh key pair
  go.mod
  go.sum
  pkg/providers/vsphere/constants.go
  pkg/providers/vsphere/preparerke.go
  pkg/providers/vsphere/vsphere.go
  pkg/utils/ssh/ssh.go
Labels: enhancement

#43 Embed cake linux
  .github/workflows/go.yml
  .gitignore
  Makefile
  go.mod
  go.sum
  hack/upx-darwin
  hack/upx-linux
  pkg/providers/vsphere/constants.go
  pkg/providers/vsphere/folder_test.go
  pkg/providers/vsphere/preparecapv.go
  pkg/providers/vsphere/provision.go
  pkg/statik/.keep
Labels: enhancement

#52 RKE cli engine deployment of rancher via helm + expose via NodePort
  cmd/deploy.go
  go.mod
  pkg/engines/rke-cli/rke-cli.go
Labels: cluster-engine

#50 Adding an RKE cleaner
  Makefile
  examples/config-rke.yaml
  hack/rke-cleanup.sh
Labels: Low Hanging Fruit

#51 Rke engine integration
  .gitignore
  go.sum
  pkg/cmds/cmds.go
  pkg/engines/rke-cli/cluster.yml.go
  pkg/engines/rke-cli/rke-cli.go
  pkg/engines/rke/rke.go
  pkg/providers/vsphere/constants.go
  pkg/providers/vsphere/preparerke.go
  pkg/providers/vsphere/provision.go
  pkg/providers/vsphere/script.go
  pkg/providers/vsphere/script_test.go
Labels: enhancement

#57 fix cloud init waiting for config file
  pkg/providers/vsphere/script.go
Labels: bug

#64 Pkg events as log messages
  cmd/deploy.go
  pkg/engine/capv/addons.go
  pkg/engine/capv/addons_test.go
  pkg/engine/capv/bootstrap.go
  pkg/engine/capv/events.go
  pkg/engine/capv/files_test.go
  pkg/engine/capv/install.go
  pkg/engine/capv/kubectl.go
  pkg/engine/capv/requiredcmds.go
  pkg/engine/interface.go
  pkg/engine/rke/rke.go
  pkg/engine/rke/rke_test.go
  pkg/engine/rkecli/rkecli.go
  pkg/progress/event.go
  pkg/progress/logging.go
  pkg/provider/interface.go
  pkg/provider/vsphere/capv.go
  pkg/provider/vsphere/client.go
  pkg/provider/vsphere/client_test.go
  pkg/provider/vsphere/ova.go
  pkg/provider/vsphere/rke.go
  pkg/provider/vsphere/tasks.go
  pkg/provider/vsphere/vm.go
  pkg/provider/vsphere/vsphere.go
Labels: enhancement

#68 refactor cli flags. unmarshal config file using yaml package
  cmd/deploy.go
  cmd/destroy.go
  cmd/genconfig.go
  cmd/root.go
  examples/config-rke.yaml
  pkg/engine/rkecli/rkecli.go
  pkg/provider/interface.go
  pkg/provider/vsphere/capv.go
  pkg/provider/vsphere/constants.go
  pkg/provider/vsphere/script.go
Labels: bug

#70 Provider interface Progress method functionality
  cmd/deploy.go
  examples/config-rke.yaml
  go.mod
  go.sum
  pkg/engine/capv/addons.go
  pkg/engine/capv/addons_test.go
  pkg/engine/capv/bootstrap.go
  pkg/engine/capv/capv.go
  pkg/engine/capv/events.go
  pkg/engine/capv/files_test.go
  pkg/engine/capv/install.go
  pkg/engine/capv/kubectl.go
  pkg/engine/capv/requiredcmds.go
  pkg/engine/interface.go
  pkg/engine/rke/rke.go
  pkg/engine/rke/rke_test.go
  pkg/engine/rkecli/rkecli.go
  pkg/progress/events.go
  pkg/progress/logging.go
  pkg/progress/progress.go
  pkg/provider/interface.go
  pkg/provider/vsphere/capv.go
  pkg/provider/vsphere/client.go
  pkg/provider/vsphere/client_test.go
  pkg/provider/vsphere/constants.go
  pkg/provider/vsphere/ova.go
  pkg/provider/vsphere/rke.go
  pkg/provider/vsphere/script.go
  pkg/provider/vsphere/tasks.go
  pkg/provider/vsphere/vm.go
  pkg/provider/vsphere/vsphere.go
Labels: discussion, enhancement

#73 fix rke cert manager issue
  cmd/deploy.go
  pkg/engine/rkecli/rkecli.go
  pkg/engine/rkecli/rkecli_test.go
  pkg/engine/rkecli/types.go
Labels: bug

#77 fix missing log lines on fatal exit from cli
  cmd/deploy.go
Labels: bug

#78 mission duration and events on successful run
  cmd/deploy.go
Labels: bug

#79 set hostname using metadata for cloud-init
  pkg/provider/vsphere/cloudinit/metadata.go
  pkg/provider/vsphere/vm.go
Labels: enhancement

#82 Prevent concurrent writes to vsphere provider maps
  pkg/provider/vsphere/ova.go
  pkg/provider/vsphere/vm.go
Labels: bug, provider-vsphere

#81 RKE cli workaround to recreate Issuer
  pkg/engine/rkecli/rkecli.go
Labels: bug, cluster-engine

#83 Provider vsphere finalize method
  Makefile
  cmd/deploy.go
  cmd/genconfig.go
  cmd/root.go
  pkg/engine/interface.go
  pkg/engine/rkecli/rkecli.go
  pkg/progress/progress.go
  pkg/progress/progress_integration_test.go
  pkg/provider/interface.go
  pkg/provider/vsphere/capv.go
  pkg/provider/vsphere/cloudinit/metadata.go
  pkg/provider/vsphere/vsphere.go
  pkg/util/cmd/cmd.go
Labels: enhancement, provider-vsphere
